package POJO;// default package
// Generated 2016-10-3 17:54:38 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Essay generated by hbm2java
 */
@Entity
@Table(name = "essay", catalog = "phenomenology")
public class Essay implements java.io.Serializable {

	private Integer id;
	private String title;
	private Date time;
	private String author;
	private String location;
	private String language;
	private int pageView;
	private String type;
	private Set<EssayAttachment> essayAttachments = new HashSet<EssayAttachment>(0);
	private Set<HomepageEssay> homepageEssays = new HashSet<HomepageEssay>(0);

	public Essay() {
	}

	public Essay(String title, Date time, String author, String location, String language, int pageView, String type) {
		this.title = title;
		this.time = time;
		this.author = author;
		this.location = location;
		this.language = language;
		this.pageView = pageView;
		this.type = type;
	}

	public Essay(String title, Date time, String author, String location, String language, int pageView, String type,
			Set<EssayAttachment> essayAttachments, Set<HomepageEssay> homepageEssays) {
		this.title = title;
		this.time = time;
		this.author = author;
		this.location = location;
		this.language = language;
		this.pageView = pageView;
		this.type = type;
		this.essayAttachments = essayAttachments;
		this.homepageEssays = homepageEssays;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "author", nullable = false)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "location", nullable = false)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "language", nullable = false)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "pageView", nullable = false)
	public int getPageView() {
		return this.pageView;
	}

	public void setPageView(int pageView) {
		this.pageView = pageView;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "essay")
	public Set<EssayAttachment> getEssayAttachments() {
		return this.essayAttachments;
	}

	public void setEssayAttachments(Set<EssayAttachment> essayAttachments) {
		this.essayAttachments = essayAttachments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "essay")
	public Set<HomepageEssay> getHomepageEssays() {
		return this.homepageEssays;
	}

	public void setHomepageEssays(Set<HomepageEssay> homepageEssays) {
		this.homepageEssays = homepageEssays;
	}

}
