package POJO;// default package
// Generated 2016-10-3 17:54:38 by Hibernate Tools 4.0.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * EssayAttachmentDao generated by hbm2java
 */
@Entity
@Table(name = "essay_attachment", catalog = "phenomenology")
public class EssayAttachment implements java.io.Serializable {

	private Integer id;
	private Essay essay;
	private String location;

	public EssayAttachment() {
	}

	public EssayAttachment(Essay essay, String location) {
		this.essay = essay;
		this.location = location;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "essayId", nullable = false)
	public Essay getEssay() {
		return this.essay;
	}

	public void setEssay(Essay essay) {
		this.essay = essay;
	}

	@Column(name = "location", nullable = false)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
