package POJO;// default package
// Generated 2016-10-6 16:39:59 by Hibernate Tools 4.0.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * HomepageEssay generated by hbm2java
 */
@Entity
@Table(name = "homepage_essay", catalog = "phenomenology")
public class HomepageEssay implements java.io.Serializable {

	private Integer id;
	private Homepage homepage;
	private int sequenceNumber;
	private String thumbnailLocation;
	private String url;

	public HomepageEssay() {
	}

	public HomepageEssay(Homepage homepage, int sequenceNumber, String thumbnailLocation, String url) {
		this.homepage = homepage;
		this.sequenceNumber = sequenceNumber;
		this.thumbnailLocation = thumbnailLocation;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homepageId", nullable = false)
	public Homepage getHomepage() {
		return this.homepage;
	}

	public void setHomepage(Homepage homepage) {
		this.homepage = homepage;
	}

	@Column(name = "sequenceNumber", nullable = false)
	public int getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	@Column(name = "thumbnailLocation", nullable = false)
	public String getThumbnailLocation() {
		return this.thumbnailLocation;
	}

	public void setThumbnailLocation(String thumbnailLocation) {
		this.thumbnailLocation = thumbnailLocation;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
