package POJO;// default package
// Generated 2016-10-3 17:54:38 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Homepage generated by hbm2java
 */
@Entity
@Table(name = "homepage", catalog = "phenomenology")
public class Homepage implements java.io.Serializable {

	private Integer id;
	private String type;
	private String language;
	private Set<HomepageEssay> homepageEssays = new HashSet<HomepageEssay>(0);

	public Homepage() {
	}

	public Homepage(String type, String language) {
		this.type = type;
		this.language = language;
	}

	public Homepage(String type, String language, Set<HomepageEssay> homepageEssays) {
		this.type = type;
		this.language = language;
		this.homepageEssays = homepageEssays;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "language", nullable = false)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "homepage")
	public Set<HomepageEssay> getHomepageEssays() {
		return this.homepageEssays;
	}

	public void setHomepageEssays(Set<HomepageEssay> homepageEssays) {
		this.homepageEssays = homepageEssays;
	}

}
