package POJO;// default package
// Generated 2016-10-3 17:54:38 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * HomepageEssay generated by hbm2java
 */
@Entity
@Table(name = "homepage_essay", catalog = "phenomenology")
public class HomepageEssay implements java.io.Serializable {

	private Integer id;
	private Essay essay;
	private Homepage homepage;
	private String tableName;
	private int sequenceNumber;
	private String thumbnailLocation;

	public HomepageEssay() {
	}

	public HomepageEssay(Essay essay, Homepage homepage, String tableName, int sequenceNumber,
			String thumbnailLocation) {
		this.essay = essay;
		this.homepage = homepage;
		this.tableName = tableName;
		this.sequenceNumber = sequenceNumber;
		this.thumbnailLocation = thumbnailLocation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "essayId", nullable = false)
	public Essay getEssay() {
		return this.essay;
	}

	public void setEssay(Essay essay) {
		this.essay = essay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homepageId", nullable = false)
	public Homepage getHomepage() {
		return this.homepage;
	}

	public void setHomepage(Homepage homepage) {
		this.homepage = homepage;
	}

	@Column(name = "tableName", nullable = false)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "sequenceNumber", nullable = false)
	public int getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

	@Column(name = "thumbnailLocation", nullable = false)
	public String getThumbnailLocation() {
		return this.thumbnailLocation;
	}

	public void setThumbnailLocation(String thumbnailLocation) {
		this.thumbnailLocation = thumbnailLocation;
	}

}
