package POJO;// default package
// Generated 2016-10-3 17:54:38 by Hibernate Tools 4.0.0

import ENUM.Language;
import ENUM.Type;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Homepage generated by hbm2java
 */
@Entity
@Table(name = "homepage", catalog = "phenomenology")
public class Homepage implements java.io.Serializable {

	private Integer id;
	private Type type;
	private Language language;
	private Set<HomepageEssay> homepageEssays = new HashSet<HomepageEssay>(0);

	public Homepage() {
	}

	public Homepage(Type type, Language language) {
		this.type = type;
		this.language = language;
	}

	public Homepage(Type type, Language language, Set<HomepageEssay> homepageEssays) {
		this.type = type;
		this.language = language;
		this.homepageEssays = homepageEssays;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "type", nullable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "language", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "homepage")
	public Set<HomepageEssay> getHomepageEssays() {
		return this.homepageEssays;
	}

	public void setHomepageEssays(Set<HomepageEssay> homepageEssays) {
		this.homepageEssays = homepageEssays;
	}

}
