package POJO;// default package
// Generated 2016-10-6 16:39:59 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person", catalog = "phenomenology")
public class Person implements java.io.Serializable {

	private Integer id;
	private String name;
	private String imageLocation;
	private String descriptionLocation;
	private String language;
	private String type;
	private int sequence;

	public Person() {
	}

	public Person(String name, String imageLocation, String descriptionLocation, String language, String type,
			int sequence) {
		this.name = name;
		this.imageLocation = imageLocation;
		this.descriptionLocation = descriptionLocation;
		this.language = language;
		this.type = type;
		this.sequence = sequence;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "imageLocation", nullable = false)
	public String getImageLocation() {
		return this.imageLocation;
	}

	public void setImageLocation(String imageLocation) {
		this.imageLocation = imageLocation;
	}

	@Column(name = "descriptionLocation", nullable = false)
	public String getDescriptionLocation() {
		return this.descriptionLocation;
	}

	public void setDescriptionLocation(String descriptionLocation) {
		this.descriptionLocation = descriptionLocation;
	}

	@Column(name = "language", nullable = false)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "sequence", nullable = false)
	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

}
