package POJO;// default package
// Generated 2016-10-3 17:54:38 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PersonPosition generated by hbm2java
 */
@Entity
@Table(name = "person_position", catalog = "phenomenology")
public class PersonPosition implements java.io.Serializable {

	private Integer id;
	private int positionId;
	private int personId;
	private int sequenceNumber;

	public PersonPosition() {
	}

	public PersonPosition(int positionId, int personId, int sequenceNumber) {
		this.positionId = positionId;
		this.personId = personId;
		this.sequenceNumber = sequenceNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "positionId", nullable = false)
	public int getPositionId() {
		return this.positionId;
	}

	public void setPositionId(int positionId) {
		this.positionId = positionId;
	}

	@Column(name = "personId", nullable = false)
	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	@Column(name = "sequenceNumber", nullable = false)
	public int getSequenceNumber() {
		return this.sequenceNumber;
	}

	public void setSequenceNumber(int sequenceNumber) {
		this.sequenceNumber = sequenceNumber;
	}

}
