package POJO;// default package
// Generated 2016-10-3 17:54:38 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Scientificachievement generated by hbm2java
 */
@Entity
@Table(name = "scientificachievement", catalog = "phenomenology")
public class Scientificachievement implements java.io.Serializable {

	private Integer id;
	private String title;
	private String type;
	private String language;
	private String thumbnailLocation;
	private String descriptionLocation;
	private Date time;
	private Set<SaAttachment> saAttachments = new HashSet<SaAttachment>(0);

	public Scientificachievement() {
	}

	public Scientificachievement(String title, String type, String language, String thumbnailLocation,
			String descriptionLocation, Date time) {
		this.title = title;
		this.type = type;
		this.language = language;
		this.thumbnailLocation = thumbnailLocation;
		this.descriptionLocation = descriptionLocation;
		this.time = time;
	}

	public Scientificachievement(String title, String type, String language, String thumbnailLocation,
			String descriptionLocation, Date time, Set<SaAttachment> saAttachments) {
		this.title = title;
		this.type = type;
		this.language = language;
		this.thumbnailLocation = thumbnailLocation;
		this.descriptionLocation = descriptionLocation;
		this.time = time;
		this.saAttachments = saAttachments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "language", nullable = false)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "thumbnailLocation", nullable = false)
	public String getThumbnailLocation() {
		return this.thumbnailLocation;
	}

	public void setThumbnailLocation(String thumbnailLocation) {
		this.thumbnailLocation = thumbnailLocation;
	}

	@Column(name = "descriptionLocation", nullable = false)
	public String getDescriptionLocation() {
		return this.descriptionLocation;
	}

	public void setDescriptionLocation(String descriptionLocation) {
		this.descriptionLocation = descriptionLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scientificachievement")
	public Set<SaAttachment> getSaAttachments() {
		return this.saAttachments;
	}

	public void setSaAttachments(Set<SaAttachment> saAttachments) {
		this.saAttachments = saAttachments;
	}

}
