package POJO;// default package
// Generated 2016-10-3 17:54:38 by Hibernate Tools 4.0.0

import ENUM.Language;
import ENUM.Type;

import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Scientificachievement generated by hbm2java
 */
@Entity
@Table(name = "scientificachievement", catalog = "phenomenology")
public class Scientificachievement implements java.io.Serializable {

	private Integer id;
	private String title;
	private Type type;
	private Language language;
	private String thumbnailLocation;
	private String descriptionLocation;
	private Date time;
	private Set<SaAttachment> saAttachments = new HashSet<SaAttachment>(0);

	public Scientificachievement() {
		title="unknown";
		type=Type.UNKNOWN;
		language=Language.ch;
		thumbnailLocation="unknown";
		descriptionLocation="unknown";
		time= Calendar.getInstance().getTime();
	}

	public Scientificachievement(String title, Type type, Language language, String thumbnailLocation,
			String descriptionLocation, Date time) {
		this.title = title;
		this.type = type;
		this.language = language;
		this.thumbnailLocation = thumbnailLocation;
		this.descriptionLocation = descriptionLocation;
		this.time = time;
	}

	public Scientificachievement(String title, Type type, Language language, String thumbnailLocation,
			String descriptionLocation, Date time, Set<SaAttachment> saAttachments) {
		this.title = title;
		this.type = type;
		this.language = language;
		this.thumbnailLocation = thumbnailLocation;
		this.descriptionLocation = descriptionLocation;
		this.time = time;
		this.saAttachments = saAttachments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "type", nullable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Enumerated(EnumType.STRING)
	@Column(name = "language", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@Column(name = "thumbnailLocation", nullable = false)
	public String getThumbnailLocation() {
		return this.thumbnailLocation;
	}

	public void setThumbnailLocation(String thumbnailLocation) {
		this.thumbnailLocation = thumbnailLocation;
	}

	@Column(name = "descriptionLocation", nullable = false)
	public String getDescriptionLocation() {
		return this.descriptionLocation;
	}

	public void setDescriptionLocation(String descriptionLocation) {
		this.descriptionLocation = descriptionLocation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scientificachievement")
	public Set<SaAttachment> getSaAttachments() {
		return this.saAttachments;
	}

	public void setSaAttachments(Set<SaAttachment> saAttachments) {
		this.saAttachments = saAttachments;
	}

}
